[project]
name = "custcodian-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "material-plausible-plugin>=0.3.0",
    "mkdocs-material>=9.6.9",
    "mkdocs-redirects>=v1.2.2",
]
