name: Publish email templates

on:
  push:
    branches:
      - main
    paths:
      - emails/**
      - .github/workflows/emails-image.yaml
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    # TODO: simplify this to use OCI volume mounts rather than copying content
    - uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4
    - name: Compute version number
      id: version-string
      run: |
        DATE="$(date +%Y%m%d)"
        COMMIT="$(git rev-parse --short HEAD)"
        echo "tag=0.$DATE.$GITHUB_RUN_NUMBER+ref.$COMMIT" >> "$GITHUB_OUTPUT"

    - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
      id: meta
      with:
        images: ghcr.io/custcodian/email-templates
        tags: ${{ steps.version-string.outputs.tag }}
  
    - name: Build image
      id: push
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7
      with:
        context: ./emails
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate attestations
      uses: actions/attest-build-provenance@4d101475d8b20a2381f78447822ac1eab6504dd8 # v4
      with:
        subject-name: ghcr.io/custcodian/email-templates
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
